name: Create codespaces prebuild
on: workflow_dispatch

jobs:
  createPrebuild:
    runs-on: ubuntu-latest
    steps:
      - id: create-prebuild
        run: |
          curl -X "POST" "https://codespaces-prebuild-spike.review-lab.github.com/api/v3/vscs_internal/user/aharpole/codespaces/prebuild" \
          -H 'User-Agent: 0cb4dc7f43688571f87c3fbda1bba50c99da01c5' \
          -H 'Content-Type: application/json; charset=utf-8' \
          -H 'Authorization: token ${{ secrets.MY_ACCESS_TOKEN }}' \
          -d $'{ 
          "ref": "master",
          "repository_id": "354153749",
          "location": "EastUs"
          }'
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo prebuld: ${{ steps.create-prebuild.outputs.data }}"
  
