name: Create codespaces prebuild
on: workflow_dispatch

jobs:
  createPrebuild:
    runs-on: ubuntu-latest
    steps:
      - id: create-prebuild
        run: |
          curl -X "POST" "https://api.github.com/vscs_internal/user/aharpole/codespaces/prebuild" \
          -H 'Content-Type: application/json; charset=utf-8' \
          -H 'Authorization: token ${{ secrets.MY_ACCESS_TOKEN }}' \
          -d $'{ 
          "ref": "master",
          "repository_id": "354153749",
          "location": "EastUs"
          }'
      - run: "echo prebuld: ${{ steps.create-prebuild.outputs.data }}"
  
